In [12]:
import numpy as np

In [14]:
my_list = [1,2,3]

In [15]:
arr = np.array(my_list)

In [16]:
arr

array([1, 2, 3])

In [17]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [26]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# Arange() can be used to quickly make arrays with numpy. Third argument is the difference between the values

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
# Linspace() returns evenly spaced values. From x to y, across z values

In [31]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [33]:
# eye() for identity matrix

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.random.rand(5)

array([0.49449473, 0.52506336, 0.02893828, 0.6299208 , 0.6751673 ])

In [44]:
np.random.rand(5,5)

array([[0.13511046, 0.39491975, 0.69254557, 0.136581  , 0.12535823],
       [0.44595214, 0.26772439, 0.18521028, 0.12561492, 0.68562558],
       [0.01962801, 0.60619629, 0.56058343, 0.63355598, 0.77492518],
       [0.52692357, 0.60058438, 0.57179648, 0.72397889, 0.40079758],
       [0.47188924, 0.12894844, 0.2902274 , 0.97350095, 0.45193762]])

In [52]:
np.random.randn(4,4)

array([[ 1.18117308, -0.55378357,  0.1814807 ,  0.61339693],
       [ 0.30611264, -0.03074411,  0.98758404, -0.92757592],
       [ 1.75349765,  1.28503957,  1.2531645 , -0.10638623],
       [ 1.52144307, -0.09318411,  1.6602042 , -1.50750818]])

In [66]:
np.random.randint(0,10,4)

array([2, 3, 7, 0])

In [67]:
# Reshape() to reshape the dimension of the matrix

In [88]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Min() and Max(). Argmax returns index value of the min/max

In [84]:
ranarr = np.random.randint(0,50,10)

In [85]:
ranarr

array([47, 45, 14,  3, 47,  8, 40, 21, 32, 13])

In [86]:
ranarr.max()

47

In [87]:
ranarr.min()

3

In [89]:
ranarr.argmax()

0

In [92]:
ranarr.argmin()

3

In [93]:
# Shape returns the dimension of the array. This is one dimensional because there is only 1 number

In [95]:
# dtype for data type

In [96]:
ranarr.dtype

dtype('int32')

## Numpy Array Indexing

In [97]:
arr = np.arange(0,11)

In [98]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr[3]

3

In [100]:
arr[3:6]

array([3, 4, 5])

In [101]:
arr[:5]

array([0, 1, 2, 3, 4])

In [102]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [127]:
## INDEXING 2D ARRAYS/MATRICES

In [128]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [129]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [132]:
# Grabbing elements from a 2D array using index

In [133]:
arr_2d[0]

array([ 5, 10, 15])

In [134]:
arr_2d[0][0]

5

In [138]:
arr_2d[2][1]

40

In [139]:
# Row index, column index

In [142]:
arr_2d[1,2]

30

In [148]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [149]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [150]:
# CONDITIONAL SELECTION

In [151]:
arr = np.arange(1,11)

In [152]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [154]:
bool_arr = arr > 5

In [155]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [156]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [158]:
arr[arr<3]

array([1, 2])

In [163]:
arr_2d[3:5,6:8]

array([[36, 37],
       [46, 47]])

## Numpy Operations

In [164]:
arr = np.arange(0,11)

In [165]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [166]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [167]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [168]:
arr / arr

<ipython-input-168-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [169]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [170]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [171]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [172]:
np.log(arr)

<ipython-input-172-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])